# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 4 * * *"
      
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
          
    - name: Python setup
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Python cached pip
      uses: actions/cache@v3
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
          
    - name: Python install requirements
      run: pip install -r requirements.txt

    - name: Generate latest feed (en)
      run:
        bin/serendipod.py en feed.rss;
        git add feed.rss

    - name: Generate latest feed (de)
      run:
        bin/serendipod.py en feed.de.rss;
        git add feed.de.rss

    - name: Generate latest feed (fr)
      run:
        bin/serendipod.py en feed.fr.rss;
        git add feed.de.rss
      
    - name: Commit new RSS feed
      run:
        git config --global user.email "action@example.org";
        git config --global user.name "Github Action";
        git commit -m"Feed update." feed.rss feed.de.rss feed.fr.rss
      
    - name: RSS push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: .
